### ISSUE TITLE
Decide on a Data Store Technology

### ISSUE THREAD

**Issue by fireland15** [fireland15/DiseaseAndClimateMining#2]
There are multiple ways of storing files, we need to discuss the benefits and challenges of using each one in order make a decision about which technology we will use for this project.

**Comment by fireland15** [comment]
Here are a couple of different ideas I have about how we can approach this:

1. Create our own data store technology. Essentially compile and store all the data into a custom file type that we can read from and put into arrays when we load the data. This is probably inefficient and will take a fair amount of work to be high performing.

2. We use a database located on a server somewhere. This would allow us to all use the same data sets while we are working on separate parts of the project. It ensures a universal schema for all of us. It will also likely be stupid fast. The problem is that I don't have a server and if no one has access to one, we won't be able to get one without paying for it.

3. We use a local database file that we keep as part of the git repository, such as sqlite, or localdb. This gets us somewhere near the speed of a dedicated db server, but we won't need a server. We will also get all the relational power of a true DBMS. Unfortunately, schema changes may be difficult to update without breaking some code or breaking dependencies. 

4. Finally we keep all our data in separate folders and load&parse them every time our application starts. This is obviously a terrible idea for obvious reasons.

**Comment by TravisLanders** [comment]
I don't have a server unless the bluehost subscription I have came with that randomly.  I like sqlite if we aren't able to have a server.

**Comment by fireland15** [comment]
We decided to use SQL CE for development and test. Once happy with the data importer process, we will push it to a real server.
